version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    working_dir: /app
    depends_on:
      - db
    volumes:
      - .:/app
    environment:
      - DATABASE_URL=sqlite:///./quizapp.db
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--reload", "--port", "8000"]
    restart: on-failure
  db:
    image: "keinos/sqlite3:latest"
    volumes:
      - ./data:/data
    command: ["sqlite3", "/data/app.db"]